name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go 1.24.2
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"
          check-latest: true
          cache-dependency-path: tik-go/go.sum
      - name: Checkout repository
        uses: actions/checkout@v4

      # Test
      - name: Run tests with coverage
        working-directory: tik-go
        run: go test -covermode=atomic -coverprofile=coverage.out ./...

      - name: Upload to Coveralls
        working-directory: tik-go
        run: |
          go install github.com/mattn/goveralls@latest
          goveralls -coverprofile=coverage.out -service=github
