name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go 1.24.2
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"
          check-latest: true
          cache-dependency-path: tik-go/go.sum
      - name: Checkout repository
        uses: actions/checkout@v4

      # Test
      - name: Calculate coverage
        working-directory: tik-go
        run: go test -v -covermode=count -coverprofile=coverage.out
      - name: Convert coverage.out to coverage.lcov
        uses: jandelgado/gcov2lcov-action@v1.1.1
      - name: Coveralls
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: tik-go/coverage.lcov
      - name: Run go vet
        working-directory: tik-go
        continue-on-error: true
        run: go vet ./...
